### PR TITLE
Updating snakeyaml to 1.26 to solve #470

### PR DESCRIPTION
**Pull request by RockyMM**
This should solve #470

https://bitbucket.org/asomov/snakeyaml/issues/377/allow-configuration-for-preventing-billion

### CODE REVIEW

**Comment by RockyMM** [comment]
Can someone do a review?

**Review by mrspaceman — APPROVED** [review]

**Comment by tjohnson-scottlogic** [comment]
Hi @RockyMM, could you point me to the PR in the DiUS/java-faker project?  I don't seem to be able to follow this.

**Comment by RockyMM** [comment]
@tjohnson-scottlogic This is the commit that resolved the issue: https://bitbucket.org/asomov/snakeyaml/commits/da11ddbd91c1f8392ea932b37fa48110fa54ed8c
Also the issue https://bitbucket.org/asomov/snakeyaml/issues/377/allow-configuration-for-preventing-billion

But actually, no need to review it yourself, as the fix has been reviewed by a third-party (RedHat) https://bugzilla.redhat.com/show_bug.cgi?id=1785376

**Comment by tjohnson-scottlogic** [comment]
Hi @RockyMM, sorry, I'm not following :)  What should we do next to close out [DiUS#470](https://github.com/DiUS/java-faker/issues/470)?  (referenced at the top of this conversation)

**Comment by RockyMM** [comment]
@tjohnson-scottlogic 
Ah, it's my fault. I am apparently retarded when it comes to GitHub. I though I created a Pull Request in DiUS, when I did not.

I will try to make a PR in DiUS now.

**Comment by RockyMM** [comment]
I think I did it. Sorry for my lack of understanding. 😇

**Comment by tjohnson-scottlogic** [comment]
Cool, thanks :)  No worries, thanks for fixing!

**Comment by floone** [comment]
Is this going to be released? As far as I can see, 1.0.2 still includes the vulnerable version of snakeyaml:
```
$ mvn dependency:tree
...
[INFO] +- com.github.javafaker:javafaker:jar:1.0.2:compile
[INFO] |  +- org.yaml:snakeyaml:jar:android:1.23:compile
...
```

**Pull request merged**
